// saga types
export const FETCH_PROFILE = "FETCH_PROFILE"
export const FETCH_UPDATE_PROFILE = "FETCH_UPDATE_PROFILE"


// Profile
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING"
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING"
//---
export const SET_PROFILE_SUCCESS = "SET_PROFILE_SUCCESS"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
//---
export const RESET_PROFILE_STATE = "RESET_PROFILE_STATE"
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR"
export const SET_EMAIL_ERROR = "SET_EMAIL_ERROR"
export const SET_PHONE_ERROR = "SET_PHONE_ERROR"
export const SET_PROFILE_ERROR = "SET_PROFILE_ERROR"


