// saga types
export const FETCH_RECEIPTS = "FETCH_RECEIPTS"
export const FETCH_UPLOAD_RECEIPT = "FETCH_UPLOAD_RECEIPT"
export const FETCH_DELETE_RECEIPT = "FETCH_DELETE_RECEIPT"

export const FETCH_RECEIPT = "FETCH_RECEIPT"
export const FETCH_UPDATE_RECEIPT = "FETCH_UPDATE_RECEIPT"


// Receipts
export const DELETE_RECEIPT = "DELETE_RECEIPT"
//---
export const SET_RECEIPTS_LOADING = "SET_RECEIPTS_LOADING"
export const UPLOAD_RECEIPT_LOADING = "UPLOAD_RECEIPT_LOADING"
export const DELETE_RECEIPT_LOADING = "DELETE_RECEIPT_LOADING"
//---
export const SET_RECEIPTS_SUCCESS = "SET_RECEIPTS_SUCCESS"
export const UPLOAD_RECEIPT_SUCCESS = "UPLOAD_RECEIPT_SUCCESS"
export const DELETE_RECEIPT_SUCCESS = "DELETE_RECEIPT_SUCCESS"
//---
export const SET_RECEIPTS_ERROR = "SET_RECEIPTS_ERROR"
export const RESET_RECEIPTS_STATE = "RESET_RECEIPTS_STATE"


// Receipt
export const SET_RECEIPT_LOADING = "SET_RECEIPT_LOADING"
export const UPDATE_RECEIPT_LOADING = "UPDATE_RECEIPT_LOADING"
//---
export const SET_RECEIPT_SUCCESS = "SET_RECEIPT_SUCCESS"
export const UPDATE_RECEIPT_SUCCESS = "UPDATE_RECEIPT_SUCCESS"
//---
export const SET_RECEIPT_ERROR = "SET_RECEIPT_ERROR"
export const RESET_RECEIPT_STATE = "RESET_RECEIPT_STATE"